/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155URIStorageUpgradeable__factory } from "./ERC1155URIStorageUpgradeable__factory";
export { IERC1155MetadataURIUpgradeable__factory } from "./IERC1155MetadataURIUpgradeable__factory";
