[profile.default]
cache_path = 'cache_forge'
fuzz = { runs = 1025 }
libs = ['node_modules', 'lib']
optimizer = true
optimizer_runs = 10000
out = 'out'
src = 'contracts'
test = 'test'

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"

[fmt]
number_underscore = "thousands"
wrap_comments = true
